spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/anime?createDatabaseIfNotExist=true}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

server:
  error:
    include-stacktrace: on-param

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql: TRACE
